from enum import Enum


class AuditAction(str, Enum):
    ACCOUNT_DELETED = "account_deleted"
    ADMIN_ASSIGNED = "admin_assigned"
    ADMIN_REMOVED = "admin_removed"
    API_ACCESS = "api_access"
    API_KEY_CREATED = "api_key_created"
    API_KEY_REVOKED = "api_key_revoked"
    API_TOKEN_CREATED = "api_token_created"
    API_TOKEN_REVOKED = "api_token_revoked"
    APPLICATION_ACCEPTED = "application_accepted"
    APPLICATION_REJECTED = "application_rejected"
    APPLICATION_SUBMITTED = "application_submitted"
    AVATAR_CHANGED = "avatar_changed"
    BUILDER_FLARE_CREATED = "builder_flare_created"
    BUILDER_FLARE_DELETED = "builder_flare_deleted"
    BUILDER_FLARE_UPDATED = "builder_flare_updated"
    EMAIL_CHANGED = "email_changed"
    FAILED_LOGIN = "failed_login"
    INVITATION_ACCEPTED = "invitation_accepted"
    INVITATION_EXPIRED = "invitation_expired"
    INVITATION_REJECTED = "invitation_rejected"
    INVITATION_REVOKED = "invitation_revoked"
    INVITATION_SENT = "invitation_sent"
    LOGIN = "login"
    LOGOUT = "logout"
    MEMBER_INVITED = "member_invited"
    MEMBER_REMOVED = "member_removed"
    ORGANIZATION_CREATED = "organization_created"
    ORGANIZATION_DELETED = "organization_deleted"
    ORGANIZATION_UPDATED = "organization_updated"
    PASSWORD_CHANGED = "password_changed"
    PASSWORD_RESET = "password_reset"
    PERMISSIONS_CHANGED = "permissions_changed"
    PROFILE_UPDATED = "profile_updated"
    PROJECT_ARCHIVED = "project_archived"
    PROJECT_CREATED = "project_created"
    PROJECT_DELETED = "project_deleted"
    PROJECT_RESTORED = "project_restored"
    PROJECT_UPDATED = "project_updated"
    REGISTER = "register"
    REPOSITORY_CONNECTED = "repository_connected"
    REPOSITORY_SYNCED = "repository_synced"
    ROLE_CHANGED = "role_changed"
    ROLE_UPDATED = "role_updated"
    SETTINGS_CHANGED = "settings_changed"
    SUSPICIOUS_LOGIN_ATTEMPT = "suspicious_login_attempt"
    TOKEN_REVOKED = "token_revoked"
    USER_ACTIVATED = "user_activated"
    USER_BANNED = "user_banned"
    USER_DEMOTED = "user_demoted"
    USER_PROMOTED = "user_promoted"
    USER_SUSPENDED = "user_suspended"
    USER_UNBANNED = "user_unbanned"

    def __str__(self) -> str:
        return str(self.value)
