apiVersion: v1
kind: ConfigMap
metadata:
  name: devlink-backend-config
data:
  ENVIRONMENT: "production"
  DEBUG: "False"
  HOST: "0.0.0.0"
  PORT: "8000"
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ALLOWED_ORIGINS: "http://devlink.local"
  LOG_LEVEL: "INFO"